name: Deploy to MonsterASP.NET

on:
  push:
    branches:
      - master  # Your branch name
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Step 2: Setup .NET 8
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore
    
    # Step 4: Build the project
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    # Step 5: Publish the project
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish --no-build
    
    # Step 6: Deploy via SFTP with password
    - name: Deploy to SFTP
      uses: pressidium/lftp-mirror-action@v1
      with:
        host: ${{ secrets.FTP_SERVER }}
        port: 22
        user: ${{ secrets.FTP_USERNAME }}
        pass: ${{ secrets.FTP_PASSWORD }}
        localDir: './publish/'
        remoteDir: '/wwwroot/WatchKids/'
        options: '--verbose'
